//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses
    {
        public courses()
        {
            this.course_assignment = new HashSet<course_assignment>();
            this.course_schedule = new HashSet<course_schedule>();
            this.modules = new HashSet<modules>();
        }
    
        public int course_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int duration { get; set; }
        public decimal cost { get; set; }
        public int type { get; set; }
    
        public virtual ICollection<course_assignment> course_assignment { get; set; }
        public virtual ICollection<course_schedule> course_schedule { get; set; }
        public virtual course_type course_type { get; set; }
        public virtual ICollection<modules> modules { get; set; }
    }
}
