//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Module
    {
        public FC_Module()
        {
            this.Mod_Content = new HashSet<Mod_Content>();
        }
    
        public int idFC_Module { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> idFile { get; set; }
    
        public virtual FileControl FileControl { get; set; }
        public virtual modules modules { get; set; }
        public virtual ICollection<Mod_Content> Mod_Content { get; set; }
    }
}
