//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileControl
    {
        public FileControl()
        {
            this.FC_Module = new HashSet<FC_Module>();
        }
    
        public int idFile { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public Nullable<sbyte> Status { get; set; }
    
        public virtual ICollection<FC_Module> FC_Module { get; set; }
    }
}
