//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int log_id { get; set; }
        public string action { get; set; }
        public string module { get; set; }
        public int user { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual users users { get; set; }
    }
}
