//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;

    public partial class owldbEntities : DbContext
    {
        public owldbEntities()
            : base("name=owldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<answer_vt> answer_vt { get; set; }
        public DbSet<course_assignment> course_assignment { get; set; }
        public DbSet<course_schedule> course_schedule { get; set; }
        public DbSet<course_type> course_type { get; set; }
        public DbSet<courses> courses { get; set; }
        public DbSet<FC_Module> FC_Module { get; set; }
        public DbSet<FileControl> FileControl { get; set; }
        public DbSet<logs> logs { get; set; }
        public DbSet<Mod_Content> Mod_Content { get; set; }
        public DbSet<module_vt> module_vt { get; set; }
        public DbSet<modules> modules { get; set; }
        public DbSet<Multi_Modulo> Multi_Modulo { get; set; }
        public DbSet<multimedia> multimedia { get; set; }
        public DbSet<pass_verif_code> pass_verif_code { get; set; }
        public DbSet<question_vt> question_vt { get; set; }
        public DbSet<questions> questions { get; set; }
        public DbSet<role_user> role_user { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<schedules> schedules { get; set; }
        public DbSet<test_type> test_type { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<virtual_tests> virtual_tests { get; set; }
        public DbSet<vt_scored_record> vt_scored_record { get; set; }

        public virtual int generateVerificationCode(string user_email)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("generateVerificationCode", user_emailParameter);
        }
    }
}
