//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modules
    {
        public modules()
        {
            this.FC_Module = new HashSet<FC_Module>();
            this.Mod_Content = new HashSet<Mod_Content>();
            this.module_vt = new HashSet<module_vt>();
            this.Multi_Modulo = new HashSet<Multi_Modulo>();
        }
    
        public int module_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int course { get; set; }
    
        public virtual courses courses { get; set; }
        public virtual ICollection<FC_Module> FC_Module { get; set; }
        public virtual ICollection<Mod_Content> Mod_Content { get; set; }
        public virtual ICollection<module_vt> module_vt { get; set; }
        public virtual ICollection<Multi_Modulo> Multi_Modulo { get; set; }
    }
}
