//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class module_vt
    {
        public int module_VT_id { get; set; }
        public System.DateTime star_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int min_grade { get; set; }
        public int module { get; set; }
        public int virtual_test { get; set; }
    
        public virtual modules modules { get; set; }
        public virtual virtual_tests virtual_tests { get; set; }
    }
}
