//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multimedia
    {
        public int idMultimedia { get; set; }
        public string Description { get; set; }
        public string Tema { get; set; }
        public string URL { get; set; }
        public int Estado { get; set; }
    }
}
