//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class questions
    {
        public questions()
        {
            this.answer_vt = new HashSet<answer_vt>();
            this.question_vt = new HashSet<question_vt>();
        }
    
        public int question_id { get; set; }
        public string question { get; set; }
        public string answer1 { get; set; }
        public string answer2 { get; set; }
        public string answer3 { get; set; }
        public string answer4 { get; set; }
        public int correct_answer { get; set; }
    
        public virtual ICollection<answer_vt> answer_vt { get; set; }
        public virtual ICollection<question_vt> question_vt { get; set; }
    }
}
