//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedules
    {
        public schedules()
        {
            this.course_assignment = new HashSet<course_assignment>();
            this.course_schedule = new HashSet<course_schedule>();
        }
    
        public int schedule_id { get; set; }
        public string day { get; set; }
        public System.TimeSpan star_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual ICollection<course_assignment> course_assignment { get; set; }
        public virtual ICollection<course_schedule> course_schedule { get; set; }
    }
}
