//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_type
    {
        public test_type()
        {
            this.virtual_tests = new HashSet<virtual_tests>();
        }
    
        public int test_type_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<virtual_tests> virtual_tests { get; set; }
    }
}
