//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        internal bool rememberme;
        public users()
        {
            this.answer_vt = new HashSet<answer_vt>();
            this.course_assignment = new HashSet<course_assignment>();
            this.logs = new HashSet<logs>();
            this.pass_verif_code = new HashSet<pass_verif_code>();
            this.role_user = new HashSet<role_user>();
            this.vt_scored_record = new HashSet<vt_scored_record>();
        }
    
        public int user_id { get; set; }
        public string dni { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<answer_vt> answer_vt { get; set; }
        public virtual ICollection<course_assignment> course_assignment { get; set; }
        public virtual ICollection<logs> logs { get; set; }
        public virtual ICollection<pass_verif_code> pass_verif_code { get; set; }
        public virtual ICollection<role_user> role_user { get; set; }
        public virtual ICollection<vt_scored_record> vt_scored_record { get; set; }
    }
}
