//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owl_Learning_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class virtual_tests
    {
        public virtual_tests()
        {
            this.module_vt = new HashSet<module_vt>();
            this.question_vt = new HashSet<question_vt>();
            this.vt_scored_record = new HashSet<vt_scored_record>();
        }
    
        public int virtual_test_id { get; set; }
        public string name { get; set; }
        public int duration { get; set; }
        public string instructions { get; set; }
        public int type { get; set; }
    
        public virtual ICollection<module_vt> module_vt { get; set; }
        public virtual ICollection<question_vt> question_vt { get; set; }
        public virtual test_type test_type { get; set; }
        public virtual ICollection<vt_scored_record> vt_scored_record { get; set; }
    }
}
