//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_assignment
    {
        public int course_id { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public int course_assign_id { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public Nullable<System.DateTime> enrollTime { get; set; }
    
        public virtual users users { get; set; }
        public virtual courses courses { get; set; }
        public virtual schedules schedules { get; set; }
    }
}
