//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FC_Module()
        {
            this.Mod_Content = new HashSet<Mod_Content>();
        }
    
        public int idFC_Module { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> idFile { get; set; }
    
        public virtual FileControl FileControl { get; set; }
        public virtual modules modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mod_Content> Mod_Content { get; set; }
    }
}
