//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mod_Content
    {
        public int idMod_Content { get; set; }
        public int module_id { get; set; }
        public int idFC_Module { get; set; }
        public int idMMod { get; set; }
    
        public virtual FC_Module FC_Module { get; set; }
        public virtual modules modules { get; set; }
        public virtual Multi_Modulo Multi_Modulo { get; set; }
    }
}
