//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mod_Content
    {
        public int idMod_Content { get; set; }
        public int module_id { get; set; }
        public int idFC_Module { get; set; }
        public int idMMod { get; set; }
    
        public virtual FC_Module FC_Module { get; set; }
        public virtual modules modules { get; set; }
        public virtual Multi_Modulo Multi_Modulo { get; set; }
    }
}
