//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multi_Modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Multi_Modulo()
        {
            this.Mod_Content = new HashSet<Mod_Content>();
        }
    
        public int idMMod { get; set; }
        public Nullable<int> idMultimedia { get; set; }
        public Nullable<int> module_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mod_Content> Mod_Content { get; set; }
        public virtual modules modules { get; set; }
        public virtual multimedia multimedia { get; set; }
    }
}
