//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pass_verif_code
    {
        public int pass_verif_code1 { get; set; }
        public int verification_code { get; set; }
        public int user_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
