//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public questions()
        {
            this.question_vt = new HashSet<question_vt>();
            this.answer_vt = new HashSet<answer_vt>();
        }
    
        public int question_id { get; set; }
        [Required(ErrorMessage = "* Ingrese la pregunta de la prueba")]
        [Display(Name = "Pregunta")]
        [StringLength(800, MinimumLength = 10)]
        public string question { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 1 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer1 { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 2 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer2 { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 3 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer3 { get; set; }


        [Required(ErrorMessage = "* Ingrese la respuesta 4 de la prueba")]
        [Display(Name = "Respuesta")]
        [StringLength(800, MinimumLength = 1)]
        public string answer4 { get; set; }
        public int correct_answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_vt> question_vt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_vt> answer_vt { get; set; }
    }
}
