//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_vt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question_vt()
        {
            this.answer_vt = new HashSet<answer_vt>();
        }
    
        public int question_vt_id { get; set; }
        public int question { get; set; }
        public int virtual_test { get; set; }
    
        public virtual questions questions { get; set; }
        public virtual virtual_tests virtual_tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_vt> answer_vt { get; set; }
    }
}
