//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        internal bool rememberme;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.logs = new HashSet<logs>();
            this.pass_verif_code = new HashSet<pass_verif_code>();
            this.role_user = new HashSet<role_user>();
            this.course_assignment = new HashSet<course_assignment>();
            this.answer_vt = new HashSet<answer_vt>();
            this.vt_scored_record = new HashSet<vt_scored_record>();
        }

        public int user_id { get; set; }

        [Required(ErrorMessage = "* Ingrese su cédula")]
        [MinLength(9, ErrorMessage ="La identificación debe ser mínimo de 9 dígitos")]
        [MaxLength(12, ErrorMessage = "La identificación debe ser máximo de 12 dígitos")]
        [Display(Name = "Cedúla")]
        [Key]
        public string dni { get; set; }

        [Required(ErrorMessage = "* Ingrese su nombre")]
        [DataType(DataType.Text)]
        public string first_name { get; set; }

        [Required(ErrorMessage = "* Ingrese su apellido")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "* Ingrese un número telefónico")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{8})$", ErrorMessage = "Número Telefónico Inválido")]
        public string phone_number { get; set; }

        [Required(ErrorMessage = "* Ingrese su correo electrónico")]
        [Display(Name = "Correo")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Required(ErrorMessage = "* Ingrese una contraseña")]
        [MinLength(9, ErrorMessage = "* La contraseña debe ser mínimo de 9 dígitos alfanuméricos.")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logs> logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pass_verif_code> pass_verif_code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role_user> role_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_assignment> course_assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_vt> answer_vt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vt_scored_record> vt_scored_record { get; set; }
    }
}
