//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class virtual_tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public virtual_tests()
        {
            this.module_vt = new HashSet<module_vt>();
            this.question_vt = new HashSet<question_vt>();
            this.vt_scored_record = new HashSet<vt_scored_record>();
        }
    
        public int virtual_test_id { get; set; }

        [Required(ErrorMessage = "* Ingrese un nombre")]
        [Display(Name = "Nombre")]
        public string name { get; set; }
        [Required(ErrorMessage = "* Ingrese la duración de la prueba")]
        [Display(Name = "Tiempo")]
        public int duration { get; set; }
        [Required(ErrorMessage = " * Ingrese las instrucciones de la prueba")]
        [Display(Name = "Instrucciones")]
        [StringLength(200, MinimumLength = 10)]
        public string instructions { get; set; }
        public int type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<module_vt> module_vt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_vt> question_vt { get; set; }
        public virtual test_type test_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vt_scored_record> vt_scored_record { get; set; }
    }
}
