//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysqltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_scored_record
    {
        public int vt_scored_record_id { get; set; }
        public int user_id { get; set; }
        public int vt_id { get; set; }
        public int total_questions { get; set; }
        public int correct_got_answer { get; set; }
        public decimal score { get; set; }
        public System.DateTime record_date { get; set; }
        public int status { get; set; }
    
        public virtual users users { get; set; }
        public virtual virtual_tests virtual_tests { get; set; }
    }
}
